apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-svc
spec:
  type: LoadBalancer
  selector:
    app: api-pod
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
    nodePort: 30080